//sfsSeedDataUtil.deleteAllSchedulingPolicies(true, true);
//sfsSeedDataUtil.backupServiceAppointmentStatusTransitions();
//sfsSeedDataUtil.resetServiceAppointmentStatusTransitions();
//sfsSeedDataUtil.backupWorkRules();
//sfsSeedDataUtil.backupSchedulingPoliciesFull();
//sfsSeedDataUtil.restoreSchedulingPoliciesFull('0693G0000018uNRQAY', false);
//sfsSeedDataUtil.backupSchedulingPolicyWorkRules();
//sfsSeedDataUtil.restoreSchedulingPolicies('0695r000001kLpF');
//sfsSeedDataUtil.restoreSchedulingPolicyWorkRules('0695r000001kLpIAAU');